name: Security Audit
on:
  push:
    branches: [ master ]
    paths: [ Cargo.toml ]
  pull_request:
    branches: [ master ]
    paths: [ Cargo.toml ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
